sudo: required
services:
  - docker

before_install:
  - docker build -t dinhnhat0401/docker-react -f Dockerfile.dev .

script:
  - docker run dinhnhat0401/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "$AWS_BUCKET_NAME"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"

